
meta <- list(
    ChocoPhlAn = data.frame(
        Title = "ChocoPhlAn mappings v0.1.0",
        Description = "Linkmap of feature pairs from ChocoPhlAn",
        BiocVersion = "3.23",
        Genome = NA,
        SourceType = "TSV",
        SourceUrl = "https://zenodo.org/records/17100034",
        SourceVersion = "v201901b",
        Species = NA,
        TaxonomyId = NA,
        Coordinate_1_based = FALSE,
        DataProvider = "bioBakery",
        Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
        RDataClass = "igraph",
        DispatchClass = "FilePath",
        Location_Prefix = "https://zenodo.org/records/18788725/files/",
        RDataPath = "ChocoPhlAn.graphml"
    ),
    GO = data.frame(
        Title = "GO mappings v0.1.0",
        Description = "Linkmap of feature pairs from GO",
        BiocVersion = "3.23",
        Genome = NA,
        SourceType = "TSV",
        SourceUrl = "https://current.geneontology.org/ontology/external2go/",
        SourceVersion = "v2026-01-23",
        Species = NA,
        TaxonomyId = NA,
        Coordinate_1_based = FALSE,
        DataProvider = "Gene Onthology",
        Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
        RDataClass = "igraph",
        DispatchClass = "FilePath",
        Location_Prefix = "https://zenodo.org/records/18788725/files/",
        RDataPath = "GO.graphml"
    ),
    GM = data.frame(
      Title = "Gut modules v0.1.0",
      Description = "Gut-brain and gut-metabolic modules from Raes Lab",
      BiocVersion = "3.23",
      Genome = NA,
      SourceType = "TSV",
      SourceUrl = "https://github.com/omixer/omixer-rpmR/tree/main/inst/extdata",
      SourceVersion = "v1.0",
      Species = NA,
      TaxonomyId = NA,
      Coordinate_1_based = FALSE,
      DataProvider = "Raes Lab",
      Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
      RDataClass = "igraph",
      DispatchClass = "FilePath",
      Location_Prefix = "https://zenodo.org/records/18788725/files/",
      RDataPath = "GM.graphml"
    ),
    KEGG = data.frame(
        Title = "KEGG mappings v0.1.0",
        Description = "Linkmap of feature pairs from KEGG",
        BiocVersion = "3.23",
        Genome = NA,
        SourceType = "TSV",
        SourceUrl = "https://www.kegg.jp/",
        SourceVersion = "v117.0 January 1 2026",
        Species = NA,
        TaxonomyId = NA,
        Coordinate_1_based = FALSE,
        DataProvider = "Kyoto Encyclopedia of Genes and Genomes",
        Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
        RDataClass = "igraph",
        DispatchClass = "FilePath",
        Location_Prefix = "https://zenodo.org/records/18788725/files/",
        RDataPath = "KEGG.graphml"
    ),
    TIGRfams = data.frame(
      Title = "TIGRfams mappings v0.1.0",
      Description = "Linkmap of feature pairs from TIGRfams",
      BiocVersion = "3.23",
      Genome = NA,
      SourceType = "TSV",
      SourceUrl = "https://ftp.ncbi.nlm.nih.gov/hmm/TIGRFAMs/release_15.0/",
      SourceVersion = "v15.0",
      Species = NA,
      TaxonomyId = NA,
      Coordinate_1_based = FALSE,
      DataProvider = "NCBI",
      Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
      RDataClass = "igraph",
      DispatchClass = "FilePath",
      Location_Prefix = "https://zenodo.org/records/18788725/files/",
      RDataPath = "TIGRfams.graphml"
    ),
    UniProt = data.frame(
        Title = "UniProt mappings v0.1.0",
        Description = "Linkmap of feature pairs from UniProt",
        BiocVersion = "3.23",
        Genome = NA,
        SourceType = "TSV",
        SourceUrl = "https://www.uniprot.org/",
        SourceVersion = "v2026_01",
        Species = NA,
        TaxonomyId = NA,
        Coordinate_1_based = FALSE,
        DataProvider = "UniProt",
        Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
        RDataClass = "igraph",
        DispatchClass = "FilePath",
        Location_Prefix = "https://zenodo.org/records/18788725/files/",
        RDataPath = "UniProt.graphml"
    ),
    WoL = data.frame(
        Title = "WoL mappings v0.1.0",
        Description = "Linkmap of feature pairs from WoL",
        BiocVersion = "3.23",
        Genome = NA,
        SourceType = "TSV",
        SourceUrl = "https://ftp.microbio.me/pub/wol-20April2021/",
        SourceVersion = "v20April2021",
        Species = NA,
        TaxonomyId = NA,
        Coordinate_1_based = FALSE,
        DataProvider = "Web of Life",
        Maintainer = "Giulio Benedetti <giulio.benedetti@utu.fi>",
        RDataClass = "igraph",
        DispatchClass = "FilePath",
        Location_Prefix = "https://zenodo.org/records/18788725/files/",
        RDataPath = "WoL.graphml"
    )
)

meta <- do.call(rbind, meta)

write.csv(meta, "metadata.csv", row.names = FALSE)

makeAnnotationHubMetadata(".")
